--INNER JOIN 4 TEBLE ----> test_INVENTITEMBARCODE, test_INVENTTABLE, test_VENDTABLE, test_DIMENSION

SELECT T1.[ITEMBARCODE], T1.[ITEMID], T1.[INVENTDIMID], T1.[UNITID], T1.[SPC_PRICEGROUP3], T1.[SPC_ITEMNAME], T1.[SPC_IMAGEPATH], T1.[SPC_ITEMBUYERGROUPID], 
	   T2.[PRIMARYVENDORID], T3.[NAME], T4.[DESCRIPTION]
FROM  [test_INVENTITEMBARCODE] T1
INNER JOIN [test_INVENTTABLE] T2 ON  T1.[ITEMID] = T2.[ITEMID]
INNER JOIN [test_VENDTABLE] T3 ON T2.[PRIMARYVENDORID] = T3.[ACCOUNTNUM]
INNER JOIN [test_DIMENSION] T4 ON T1.[SPC_ITEMBUYERGROUPID] = T4.[NUM]


INSERT INTO  ([ACCOUNTNUM],[NAME],[DATAAREAID])